#+title: My homepage with org-mode
#+author: Seth Doty
#+date: <2021-01-01 Fri>

[[https://github.com/sethmdoty/sethmdoty.github.io/workflows/Build%20and%20publish%20to%20pages/badge.svg][https://github.com/sethmdoty/sethmdoty.github.io/workflows/Build%20and%20publish%20to%20pages/badge.svg]]

* Introduction

This setup based on [[https://orgmode.org][org-mode]] and heavily based on ideas from https://github.com/dmacvicar/site.org.

* Implementation

For details about the implementation see the [[https://github.com/sethmdoty/sethmdoty.github.io][Github Source]].

* Usage

- Posts go into =posts/=
  Preferably in their own subdirectory together with all their assets (self-contained)

To generate:

#+BEGIN_EXAMPLE
$ make
#+END_EXAMPLE

The output site will be rendered in =public/=.

** RSS Feeds

This part is complicated and easy to forget how it works everytime something breaks.

- Each export block in the project translates the full site, file by file, to another format (taking into account excludes, includes)

- Sitemaps allow to generate a map of all converted files in a single org file.
  Eg. a sitemap in posts, will generate an org file with a list of links to all posts. This is particularly useful for the rss exporter.

- We have an export entry in the project that goes over __posts/_, takes a dummy export function, but generates a sitemap. This allows us to end with a _rss.org_ file without really exporting anything.

- Then we use another entry in the project, that uses the _RSS_ exporter, including only _rss.org_ in order to generate _rss.xml_

- Now, the default sitemap function generates something like:

  #+BEGIN_SRC txt
    * Entries
      - [[One entry][http://link]]
      - [[Second entry][http://link]]
  #+END_SRC

  Those will not be exported correctly to a list of links. Only the headline  will be exported in the RSS file.

  #+BEGIN_SRC txt
    * [[One entry][http://link]]
    * [[Second entry][http://link]]
  #+END_SRC

- By default, the link will reference the file where the link appears. Something like
  #+BEGIN_SRC txt
  <link>http://rss.org#section</link>
  #+END_SRC

  To change this we use _org-rss-use-entry-url-as-guid_ and set the _RSS_PERMALINK_ property of the headline when generating the sitemap.
  The _RSS_ exporter will then use the property for the _<link>_ tag content.

- The custom entry formatter adds a headline to a temp buffer and then uses _org-set-property_ to set the custom properties.
- The sitemap function uses _org-list-to-generic_ to create a list of headlines without adding a star, as it will be added by the entry function.

* Features

** Drafts

 To hide a post from the list of recent posts or the full archive, use:

  #+BEGIN_SRC org
  #+DRAFT t
  #+END_SRC
 
  Note that the post will still be published, but you will need to access it by its URL directly.

* License

The code used for generating the site is licensed under the [[file:LICENSE][MIT]] license.

The content of the site, Copyright (©) 2021 Seth Doty.
